// Generated by CoffeeScript 1.7.1
(function() {
  var CachedFind, EventEmitter, MongoOplog, Promise, getWatcher, sift, watchers,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  sift = require('sift');

  MongoOplog = require('mongo-oplog');

  Promise = require('bluebird');

  EventEmitter = require('events').EventEmitter;

  watchers = {};

  getWatcher = function(collection) {
    var address, host, port;
    host = collection.db.serverConfig._state.master.host;
    port = collection.db.serverConfig._state.master.port;
    address = collection.db.options.url.replace(/\/[^\/]+$/, '/local');
    if (!watchers[address]) {
      watchers[address] = new Promise(function(resolve, reject) {
        var watcher;
        watcher = MongoOplog(address);
        return watcher.tail(function() {
          return resolve(watcher);
        });
      });
    }
    return watchers[address];
  };

  module.exports = CachedFind = (function(_super) {
    __extends(CachedFind, _super);

    function CachedFind(collection, query) {
      var ns;
      this.collection = collection;
      this.query = query;
      ns = collection.db.databaseName + '.' + collection.collectionName;
      this.sifter = sift(query);
      this.documents = {};
      this.refresh();
      this.watcher = getWatcher(collection);
      this.watcher.then((function(_this) {
        return function(watcher) {
          _this.emit('tailing', watcher);
          watcher.on('insert', function(event) {
            if (event.ns === ns) {
              if (_this.check(event.o)) {
                return _this.add(event.o);
              }
            }
          });
          watcher.on('update', function(event) {
            if (event.ns === ns) {
              if (_this.check(event.o)) {
                return _this.add(event.o);
              } else {
                return _this.remove(event.o._id);
              }
            }
          });
          return watcher.on('remove', function(event) {
            if (event.ns === ns) {
              return _this.remove(event.o._id);
            }
          });
        };
      })(this));
    }

    CachedFind.prototype.refresh = function(callback) {
      return this.query = new Promise((function(_this) {
        return function(resolve, reject) {
          return _this.collection.find(_this.query).toArray(function(err, rows) {
            var row, _i, _len;
            _this.documents = {};
            if (err) {
              _this.emit('error', err);
              return reject(err);
            } else {
              for (_i = 0, _len = rows.length; _i < _len; _i++) {
                row = rows[_i];
                _this.documents[row._id] = row;
              }
              _this.emit('init', rows);
              return resolve();
            }
          });
        };
      })(this));
    };

    CachedFind.prototype.check = function(document) {
      return this.sifter.test(document);
    };

    CachedFind.prototype.add = function(document) {
      this.documents[document._id] = document;
      return this.emit('add', document);
    };

    CachedFind.prototype.remove = function(id) {
      if (this.documents[id]) {
        delete this.documents[id];
        return this.emit('remove', this.documents[id]);
      }
    };

    CachedFind.prototype.get = function(cb) {
      var bad, good;
      good = (function(_this) {
        return function() {
          var doc, id;
          return cb(null, (function() {
            var _ref, _results;
            _ref = this.documents;
            _results = [];
            for (id in _ref) {
              doc = _ref[id];
              if (doc) {
                _results.push(doc);
              }
            }
            return _results;
          }).call(_this));
        };
      })(this);
      bad = function(reason) {
        return cb(reason);
      };
      return this.query.then(good, bad);
    };

    return CachedFind;

  })(EventEmitter);

}).call(this);
